version: '2'

services:
  postgres:
    build:
      context: ./
      dockerfile: postgres.dockerfile
    container_name: postgres
    env_file: ./postgres.env
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    networks:
      - growth_network

  adminer:
    image: adminer
    depends_on:
      - postgres
    ports:
      - "8000:8080"
    networks:
      - growth_network

volumes:
  dbdata:

networks:
  growth_network:
