version: '2'

services:

  nginx:
    build:
      context: ../
      dockerfile: ./docker/nginx.dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../dist:/data/nginx/pages:rw
    ports:
      - "80:80"
    networks:
      - growth_network

networks:
  growth_network:
