version: '2'

services:
  postgres:
    build:
      context: ./
      dockerfile: postgres.dockerfile
    container_name: postgres
    env_file: ./postgres.env
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    networks:
      - growth_network

  adminer:
    image: adminer
    depends_on:
      - postgres
    ports:
      - "8000:8080"
    networks:
      - growth_network

  nginx:
    build:
      context: ../
      dockerfile: ./docker/nginx.dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../dist:/data/nginx/pages:rw
    ports:
      - "80:80"
    networks:
      - growth_network

volumes:
  dbdata:

networks:
  growth_network:
